CREATE TABLE segment_expansion_publications (
    id BINARY(16) NOT NULL,
    segment_publication_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    segment_id BINARY(16) NOT NULL,
    object_kind ENUM('SHARED_HUB_ADMISSION', 'MESH_MEMBERSHIP', 'DYNAMIC_ROUTE_SNAPSHOT') NOT NULL,
    policy_id BINARY(16) NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    segment_generation BIGINT UNSIGNED NOT NULL,
    segment_content_hash BINARY(32) NOT NULL,
    site_id BINARY(16) NULL,
    attachment_id BINARY(16) NULL,
    content_hash BINARY(32) NOT NULL,
    signed_envelope MEDIUMBLOB NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_expansion_version (tenant_id, segment_id, object_kind, policy_id, generation),
    KEY idx_expansion_publication (segment_publication_id),
    KEY idx_expansion_site (tenant_id, segment_id, site_id, attachment_id),
    CONSTRAINT fk_expansion_segment_publication FOREIGN KEY (segment_publication_id) REFERENCES segment_route_publications(id),
    CONSTRAINT fk_expansion_segment FOREIGN KEY (tenant_id, segment_id) REFERENCES segments(tenant_id, id),
    CHECK (generation > 0),
    CHECK (segment_generation > 0),
    CHECK ((object_kind = 'MESH_MEMBERSHIP' AND site_id IS NOT NULL AND attachment_id IS NOT NULL) OR (object_kind <> 'MESH_MEMBERSHIP' AND site_id IS NULL AND attachment_id IS NULL))
) ENGINE=InnoDB;
