-- Terminal client control-plane identity is deliberately separate from existing
-- node and site-runtime control records. These tables never carry business traffic.

CREATE TABLE client_devices (
    id BINARY(16) NOT NULL PRIMARY KEY,
    organization_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    device_id BINARY(16) NOT NULL,
    platform ENUM('WINDOWS','MACOS','ANDROID') NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    install_id VARCHAR(128) NOT NULL,
    client_version VARCHAR(64) NULL,
    status ENUM('ACTIVE','SUSPENDED','REVOKED') NOT NULL DEFAULT 'ACTIVE',
    generation BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    last_seen_at TIMESTAMP(6) NULL,
    revoked_at TIMESTAMP(6) NULL,
    UNIQUE KEY uq_client_devices_tenant_device (tenant_id, device_id),
    UNIQUE KEY uq_client_devices_tenant_install (tenant_id, install_id),
    UNIQUE KEY uq_client_devices_binding (id, organization_id, tenant_id, user_id),
    KEY idx_client_devices_user (tenant_id, user_id, status),
    CONSTRAINT fk_client_devices_organization FOREIGN KEY (organization_id) REFERENCES organizations(id),
    CONSTRAINT fk_client_devices_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_client_devices_user FOREIGN KEY (user_id) REFERENCES human_users(id),
    CONSTRAINT client_devices_generation_positive CHECK (generation >= 1)
) ENGINE=InnoDB;

CREATE TABLE client_device_keys (
    id BINARY(16) NOT NULL PRIMARY KEY,
    organization_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    client_device_id BINARY(16) NOT NULL,
    device_key_id BINARY(16) NOT NULL,
    public_key VARBINARY(64) NOT NULL,
    status ENUM('ACTIVE','RETIRED','REVOKED') NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    revoked_at TIMESTAMP(6) NULL,
    UNIQUE KEY uq_client_device_keys_tenant_key (tenant_id, device_key_id),
    UNIQUE KEY uq_client_device_keys_binding (client_device_id, device_key_id, organization_id, tenant_id, user_id),
    KEY idx_client_device_keys_device (tenant_id, client_device_id, status),
    CONSTRAINT fk_client_device_keys_organization FOREIGN KEY (organization_id) REFERENCES organizations(id),
    CONSTRAINT fk_client_device_keys_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_client_device_keys_user FOREIGN KEY (user_id) REFERENCES human_users(id),
    CONSTRAINT fk_client_device_keys_device FOREIGN KEY (client_device_id, organization_id, tenant_id, user_id) REFERENCES client_devices(id, organization_id, tenant_id, user_id),
    CONSTRAINT client_device_keys_public_key_bounded CHECK (OCTET_LENGTH(public_key) BETWEEN 32 AND 64)
) ENGINE=InnoDB;

CREATE TABLE client_grants (
    id BINARY(16) NOT NULL PRIMARY KEY,
    organization_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    client_device_id BINARY(16) NOT NULL,
    device_key_id BINARY(16) NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    request_id BINARY(16) NOT NULL,
    request_hash BINARY(32) NOT NULL,
    signing_key_id VARCHAR(128) NOT NULL,
    grant_digest BINARY(32) NOT NULL,
    grant_envelope BLOB NOT NULL,
    issued_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    status ENUM('ACTIVE','REVOKED','EXPIRED') NOT NULL DEFAULT 'ACTIVE',
    revoked_at TIMESTAMP(6) NULL,
    UNIQUE KEY uq_client_grants_request (tenant_id, client_device_id, request_id),
    UNIQUE KEY uq_client_grants_digest (tenant_id, grant_digest),
    UNIQUE KEY uq_client_grants_binding (id, organization_id, tenant_id, user_id, client_device_id, device_key_id),
    KEY idx_client_grants_active (tenant_id, client_device_id, device_key_id, status, generation),
    CONSTRAINT fk_client_grants_organization FOREIGN KEY (organization_id) REFERENCES organizations(id),
    CONSTRAINT fk_client_grants_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_client_grants_user FOREIGN KEY (user_id) REFERENCES human_users(id),
    CONSTRAINT fk_client_grants_device FOREIGN KEY (client_device_id, organization_id, tenant_id, user_id) REFERENCES client_devices(id, organization_id, tenant_id, user_id),
    CONSTRAINT fk_client_grants_key FOREIGN KEY (client_device_id, device_key_id, organization_id, tenant_id, user_id) REFERENCES client_device_keys(client_device_id, device_key_id, organization_id, tenant_id, user_id),
    CONSTRAINT client_grants_generation_positive CHECK (generation >= 1),
    CONSTRAINT client_grants_time_order CHECK (expires_at > issued_at)
) ENGINE=InnoDB;

CREATE TABLE client_projections (
    id BINARY(16) NOT NULL PRIMARY KEY,
    organization_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    client_device_id BINARY(16) NOT NULL,
    device_key_id BINARY(16) NOT NULL,
    grant_id BINARY(16) NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    content_hash BINARY(32) NOT NULL,
    projection_envelope MEDIUMBLOB NOT NULL,
    issued_at TIMESTAMP(6) NOT NULL,
    stale_until TIMESTAMP(6) NOT NULL,
    status ENUM('PUBLISHED','REVOKED','SUPERSEDED') NOT NULL DEFAULT 'PUBLISHED',
    revoked_at TIMESTAMP(6) NULL,
    UNIQUE KEY uq_client_projections_generation (tenant_id, client_device_id, generation),
    UNIQUE KEY uq_client_projections_hash (tenant_id, client_device_id, content_hash),
    UNIQUE KEY uq_client_projections_binding (id, organization_id, tenant_id, user_id, client_device_id, device_key_id, grant_id),
    UNIQUE KEY uq_client_projections_receipt_binding (id, organization_id, tenant_id, user_id, client_device_id, device_key_id),
    KEY idx_client_projections_current (tenant_id, client_device_id, device_key_id, status, generation),
    CONSTRAINT fk_client_projections_organization FOREIGN KEY (organization_id) REFERENCES organizations(id),
    CONSTRAINT fk_client_projections_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_client_projections_user FOREIGN KEY (user_id) REFERENCES human_users(id),
    CONSTRAINT fk_client_projections_device FOREIGN KEY (client_device_id, organization_id, tenant_id, user_id) REFERENCES client_devices(id, organization_id, tenant_id, user_id),
    CONSTRAINT fk_client_projections_grant FOREIGN KEY (grant_id, organization_id, tenant_id, user_id, client_device_id, device_key_id) REFERENCES client_grants(id, organization_id, tenant_id, user_id, client_device_id, device_key_id),
    CONSTRAINT client_projections_generation_positive CHECK (generation >= 1),
    CONSTRAINT client_projections_time_order CHECK (stale_until > issued_at)
) ENGINE=InnoDB;

CREATE TABLE client_projection_receipts (
    id BINARY(16) NOT NULL PRIMARY KEY,
    organization_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    client_device_id BINARY(16) NOT NULL,
    device_key_id BINARY(16) NOT NULL,
    projection_id BINARY(16) NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    content_hash BINARY(32) NOT NULL,
    request_id BINARY(16) NOT NULL,
    state ENUM('RECEIVED','VERIFIED','STAGED','COMMITTED','REJECTED') NOT NULL,
    error_code VARCHAR(80) NULL,
    reported_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_client_projection_receipt_request (tenant_id, client_device_id, request_id),
    UNIQUE KEY uq_client_projection_receipts_binding (id, organization_id, tenant_id, user_id, client_device_id, device_key_id),
    KEY idx_client_projection_receipts_projection (tenant_id, client_device_id, projection_id, generation),
    CONSTRAINT fk_client_projection_receipts_organization FOREIGN KEY (organization_id) REFERENCES organizations(id),
    CONSTRAINT fk_client_projection_receipts_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_client_projection_receipts_user FOREIGN KEY (user_id) REFERENCES human_users(id),
    CONSTRAINT fk_client_projection_receipts_device FOREIGN KEY (client_device_id, organization_id, tenant_id, user_id) REFERENCES client_devices(id, organization_id, tenant_id, user_id),
    CONSTRAINT fk_client_projection_receipts_projection FOREIGN KEY (projection_id, organization_id, tenant_id, user_id, client_device_id, device_key_id) REFERENCES client_projections(id, organization_id, tenant_id, user_id, client_device_id, device_key_id),
    CONSTRAINT client_projection_receipts_generation_positive CHECK (generation >= 1)
) ENGINE=InnoDB;
