[package]
name = "cloud-worker"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
cloud-core-module = { path = "../cloud-core-module" }
chrono.workspace = true
cloud-db = { path = "../cloud-db" }
cloud-control = { path = "../cloud-control" }
ed25519-dalek.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
serde_json.workspace = true
