#!/bin/bash
set -euo pipefail
mysql -uroot -p"$MYSQL_ROOT_PASSWORD" <<SQL
CREATE USER IF NOT EXISTS 'cloud_migrator'@'%' IDENTIFIED BY '${MYSQL_MIGRATOR_PASSWORD}';
CREATE USER IF NOT EXISTS 'cloud_api'@'%' IDENTIFIED BY '${MYSQL_API_PASSWORD}';
CREATE USER IF NOT EXISTS 'cloud_identity'@'%' IDENTIFIED BY '${MYSQL_IDENTITY_PASSWORD}';
CREATE USER IF NOT EXISTS 'cloud_auth'@'%' IDENTIFIED BY '${MYSQL_AUTH_PASSWORD}';
CREATE USER IF NOT EXISTS 'cloud_worker'@'%' IDENTIFIED BY '${MYSQL_WORKER_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${MYSQL_DATABASE}\`.* TO 'cloud_migrator'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`${MYSQL_DATABASE}\`.* TO 'cloud_api'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`${MYSQL_DATABASE}\`.* TO 'cloud_identity'@'%';
GRANT SELECT, INSERT, UPDATE ON \`${MYSQL_DATABASE}\`.* TO 'cloud_auth'@'%';
GRANT SELECT, INSERT, UPDATE ON \`${MYSQL_DATABASE}\`.* TO 'cloud_worker'@'%';
FLUSH PRIVILEGES;
SQL
